feat: 🎸 add kevin todo list v1
Rabbittee/workshop-react pull request #17
Opened 2022-04-04 16:49 UTC by kevinshu1995

拖了好久.. 哈哈..

請收下我的膝蓋 orz

2022-04-05 09:45 UTC, ashramwen requested changes
加一個 bonus 給你，可以和 context 一起使用
在刪除 item 的時候跳 modal 詢問是否刪除

2022-04-05 09:45 UTC, ashramwen commented on src/pages/Kevin/TodoList/js/helpers.js
> +};
命名上 `util` 會比 `js` 好

`helper` 也應該比較明確一點命名，例如是 dateHelper 或是 mathHelper 什麼

2022-04-05 09:45 UTC, ashramwen commented on src/pages/Kevin/TodoList/TodoList.jsx
> +        return todoItems.sort((a, b) => b.isCompleted === true && -1);
這招有點厲害，不過要注意 `sort` 會造成 mutation
所以會先建議
```js
[...todoItems].sort(...)
```

2022-04-05 09:45 UTC, ashramwen commented on src/pages/Kevin/TodoList/TodoList.jsx
> +        return todoItems.sort((a, b) => b.isCompleted === true && -1);
建議這種類 enum 不要用字串
```js
const state = {
  completed: 'completed',
  onProcessing: 'completed',
  all: 'all',
};
```
實際的 value 就看要存到db的時候要存123或是字串，如果不需要儲存就沒差

2022-04-05 09:45 UTC, ashramwen commented on src/pages/Kevin/TodoList/TodoList.jsx
> +          <select
直接在 select 上面綁 `onChange` 就好了，form 是多餘的

2022-04-05 09:45 UTC, ashramwen commented on src/pages/Kevin/TodoList/components/TodoItems.jsx
> +    </form>
```jsx
{isEdit ? (
  <form>
    ...
  </form>
) : (
  <div> ... </div>
)}
```

2022-04-05 09:45 UTC, ashramwen commented on src/pages/Kevin/TodoList/components/TodoItems.jsx
> +        <div className="flex items-center gap-4">
onClickForm 實際上可以綁在這即可，所以也不叫 onClickForm 了

2022-04-05 09:45 UTC, ashramwen commented on src/pages/Kevin/TodoList/components/TodoItems.jsx
> +      onClick={onClickForm}
編輯模式不會 toggle status，所以不應該綁在這

2022-04-06 07:02 UTC, kevinshu1995 commented on src/pages/Kevin/TodoList/components/TodoItems.jsx
> +    if (isClickInput || isClickLabel) return;
收到，這邊我會調整調整

2022-04-06 07:02 UTC, kevinshu1995 commented on src/pages/Kevin/TodoList/components/TodoItems.jsx
> +    <form
了解!

2022-04-06 07:04 UTC, kevinshu1995 commented on src/pages/Kevin/TodoList/components/TodoItems.jsx
> +        className={clsx([isEdit ? 'block' : 'hidden', 'flex items-center justify-between gap-4'])}
其實原本有用，但他有報錯，我想都沒想就改成這樣XD
我再研究研究一下報了甚麼錯

2022-04-06 07:05 UTC, kevinshu1995 commented on src/pages/Kevin/TodoList/js/helpers.js
> +};
收到 !

2022-04-06 07:16 UTC, kevinshu1995 commented on src/pages/Kevin/TodoList/TodoList.jsx
> +        return todoItems.sort((a, b) => b.isCompleted === true && -1);
> 建議這種類 enum 不要用字串
> 
> ```js
> const state = {
>   completed: 'completed',
>   onProcessing: 'completed',
>   all: 'all',
> };
> ```
> 
> 實際的 value 就看要存到db的時候要存123或是字串，如果不需要儲存就沒差

請問目的是方便管理嗎

2022-04-09 15:17 UTC, kevinshu1995 commented
Update

1. 可樂的 requesting changes
2. timestamp 改成其他格式
3. 使用 useContext
4. bonus feature - show confirm modal before deleting
5. toast component

2022-04-11 01:58 UTC, haha861924 commented
凱文的吐司好屌哦

2022-04-11 14:58 UTC, ericacadu commented
凱文超強！朝聖留名！

2022-04-18 06:08 UTC, ashramwen commented on src/pages/Kevin/TodoList/TodoList.jsx
> +        return todoItems.sort((a, b) => b.isCompleted === true && -1);
避免 typo，方便管理也是，也讓後續的擴充性比較好

2022-04-18 06:14 UTC, ashramwen approved these changes

2022-04-18 06:14 UTC, ashramwen commented on src/pages/Kevin/TodoList/components/TodoDeleteModal.jsx
> +import Icon from './svg/index.js';
```js
import Icon from './svg';
```
即可

2022-04-18 06:14 UTC, merged