feat: add erica todolist solution
Rabbittee/workshop-react pull request #3
Opened 2022-02-27 04:32 UTC by ericacadu

2022-02-27 11:34 UTC, ashramwen requested changes
是不是沒開 prettier?

2022-02-27 11:34 UTC, ashramwen commented on src/pages/Erica/TodoList/components/TodoItem.jsx
> +        )}>{title}</span> }
只有 else 需要 rendering，可以不需要使用 ternary

```jsx
{!isEdit && (
  <span className={clsx('mx-1.5 px-3 py-1.5', isDone && 'line-through')}>{title}</span>
)}
```

2022-02-27 11:34 UTC, ashramwen commented on src/pages/Erica/TodoList/components/TodoItem.jsx
> +      { isEdit ? <Input value={title} onInput={(todo) => updateTodo(todo, id)} /> : '' }
這邊也是用 `&&` 即可

2022-02-27 11:34 UTC, ashramwen commented on src/pages/Erica/TodoList/components/TodoItem.jsx
> +        <Checkbox done={isDone} id={`todo-${id}`} />
label 包 input 的話就不需要給 id 和 htmlFor 了，可以直接拿掉

2022-02-27 11:34 UTC, ashramwen commented on src/pages/Erica/TodoList/components/Checkbox.jsx
> +  }
在這 case 可以把 else 拿掉，看起來會乾淨一點 (自以為)

```js
if (true)
  return ...;

return ...;
```

2022-02-27 11:34 UTC, ashramwen commented on src/pages/Erica/TodoList/components/Checkbox.jsx
> +import { CheckCircleIcon as CheckIconOutline } from '@heroicons/react/outline';
這兩個 as 的用意不明，也無意義

2022-02-27 11:34 UTC, ashramwen commented on src/pages/Erica/TodoList/components/Button.jsx
> +  const style = color || 'bg-slate-400 hover:bg-slate-600';
```js
function Button({ text, color = 'bg-slate-400 hover:bg-slate-600', onClick })
```

2022-02-27 11:34 UTC, ashramwen commented on src/pages/Erica/TodoList/TodoList.jsx
> +    setTodos(() => [...todos, newTodo]);
```js
setTodos([newTodo, ...todos]);
```

這樣就不需要再 reverse，而且直接給值就好，不需要給 function

2022-02-27 11:34 UTC, ashramwen commented on src/pages/Erica/TodoList/TodoList.jsx
> +  const [id, setId] = useState(todos.length || 0);
`todos.length || 0` 會有 bugs

當使用者刪除，再重新整理畫面新增 items 時，key 會重複
其實這個案例不需要額外建立 id state 來處理，只要取最新一筆的 item，再把它的 id + 1 即可

2022-02-27 11:34 UTC, ashramwen commented on src/pages/Erica/TodoList/components/TodoItem.jsx
> +  return (
這上面空一行，閱讀性比較好

2022-03-03 15:40 UTC, ericacadu commented on src/pages/Erica/TodoList/components/Checkbox.jsx
> +import { CheckCircleIcon as CheckIconOutline } from '@heroicons/react/outline';
這邊是兩個同樣名稱但不同樣式的 icon
一個是 solid 一個是 outline

2022-03-04 01:33 UTC, ashramwen requested changes
城市很乾淨
品質很好

2022-03-04 01:33 UTC, ashramwen commented on src/pages/Erica/TodoList/TodoList.jsx
> +      id: todo.length + 1,
不能用 length
如果刪除，length 就會改變了
可以取最後一筆的 id 再 + 1

2022-03-04 01:33 UTC, ashramwen commented on src/pages/Erica/TodoList/TodoList.jsx
> +    setValue(e.target.value.trim());
這時候做 trim 的話，使用者想輸入空白鍵就無法了
應該是在 add 的時候做比較好

2022-03-04 01:33 UTC, ashramwen commented on src/pages/Erica/TodoList/TodoList.jsx
> +  const [todo, setTodo] = useState(storage().get());
value 改變的時候會引發 re-render (這是正常的，別緊張)
如同我上次說的，每次 re-render 時會一直觸發呼叫 `storage().get()`
這邊可以改成 `useState(() => storage().get());`
在 init 的時候呼叫一次就好

https://www.notion.so/rabbit-church/useState-and-State-3d29ac55a85743cab5d20fe7c1e5dd47
最下面

2022-03-04 01:33 UTC, ashramwen commented on src/pages/Erica/TodoList/components/TodoItem.jsx
> +import { Button, Input, Checkbox } from './index';
這邊很神奇的 index 可以省略
```js
import { Button, Input, Checkbox } from './';
```
不過有些公司會希望把 index 寫上去，比較清楚
就看個人習慣自己斟酌吧

2022-03-13 13:49 UTC, ashramwen requested changes
補充一個
同時有 `yarn.lock` 和 `package-lock.json`

2022-03-14 08:38 UTC, HuskyHsu commented on src/pages/Erica/TodoList/components/Button.jsx
> +  const style = color || 'bg-slate-400 hover:bg-slate-600';
可樂～請問一下
有給default的 props 是不是建議擺放到最後面啊？
```js
function Button({ text, onClick, color = 'bg-slate-400 hover:bg-slate-600' })
```

2022-03-14 11:43 UTC, ashramwen commented on src/pages/Erica/TodoList/components/Button.jsx
> +  const style = color || 'bg-slate-400 hover:bg-slate-600';
解構的話，順序沒差
不過確實可以排序一下比較好閱讀
我個人是習慣變數在前面，fn 在後面

2022-03-14 13:09 UTC, HuskyHsu commented on src/pages/Erica/TodoList/components/Button.jsx
> +  const style = color || 'bg-slate-400 hover:bg-slate-600';
對耶，是放在解構裡面，所以不影響!!誤會了

2022-04-02 12:20 UTC, ericacadu commented on src/pages/Erica/TodoList/TodoList.jsx
> +      id: todo.length + 1,
感謝可樂提點
但是用 length 的話在初始值會取不到 id 造成錯誤
所以後來還是改成用 Date.now() 的方式給 id

2022-04-03 08:15 UTC, merged