feat: husky todolist homework!
Rabbittee/workshop-react pull request #7
Opened 2022-03-02 14:43 UTC by HuskyHsu

沒想到我是第三名!!~~再麻煩可樂大了!

目前覺得`Item`這隻裡面的一些做狀態的切換寫起來不夠乾爽
但沒頭緒怎麼調整比較好

先感謝賜教XD

![](http://memenow.cc/wp-content/uploads/2020/04/20200408_5e8ddc516af55.jpg)

2022-03-03 07:08 UTC, haha861924 commented
~~其實是 no.4 阿法已經 merge 惹~~

2022-03-03 09:10 UTC, HuskyHsu commented
> ~其實是 no.4 阿法已經 merge 惹~

什麼！！！真不愧是大阿法！！

2022-03-04 02:47 UTC, ashramwen requested changes
元件化做得很好

把每個 component 當作是一個 class
state 和 function 都是其 private members
props 就是外部傳入給 constructor 的參數

2022-03-04 02:47 UTC, ashramwen commented on src/pages/Husky/TodoList/TodoList.jsx
> +      />
這方法 ok，DI 意謂，做一個 container，裡面的 item 可以隨意 inject
react 有個東西叫 children （其他框架也有類似東西)
這樣看起來會乾淨一點

```jsx
<List>
  {todoList.map((task) => (
    <Item
      key={task.id}
      task={task}
      clickDelete={() => methods.delete(task.id)}
      editTask={(newTitle) => methods.edit(task.id, newTitle)}
      onClick={() => methods.toggleTask(task.id)}
      clickEdit={() => methods.toggleEditTask(task.id)}
    />
  ))}
</List>
```

```jsx
export function List({ children }) {
  return (
    <div className="container mx-auto flex w-full max-w-lg flex-col items-center justify-center">
      <ul className="flex w-full flex-col">{children}</ul>
    </div>
  );
}
```

2022-03-04 02:47 UTC, ashramwen commented on src/pages/Husky/TodoList/components/icon/add.jsx
> +    </svg>
比較不建議 inline
通常會拉出去成 `.svg`
而 CRA 用 svg 有兩種方式

```jsx
import logo from './logo.svg';

<img src={logo} className="App-logo" alt="logo" />
```

或是當 component 用

```jsx
import { ReactComponent as Phone } from '../images/phone.svg' ;

<Phone />
```

2022-03-04 02:47 UTC, ashramwen commented on src/pages/Husky/TodoList/components/icon/add.jsx
> +    </svg>
注意這些是 build tool 做的事，vite 就要另外裝 react svg plugin 來處理

2022-03-04 02:47 UTC, ashramwen commented on src/pages/Husky/TodoList/TodoList.jsx
> +  const [newTalk, setNewTalk] = useState();
建議可以給的 default
```js
useState('');
```

2022-03-04 02:47 UTC, ashramwen commented on src/pages/Husky/TodoList/methods.js
> +    }
useState 有給 default 的話，這邊只要判斷空字串即可
另外可以先 trim

2022-03-04 02:47 UTC, ashramwen commented on src/pages/Husky/TodoList/TodoList.jsx
> +  const methods = new TodoListMethods(todoList, setTodoList);
邏輯要另外抽出的話，可以在 custom hook 中實作
我還沒講到，有興趣的話你可以自行去找找
要注意 custom hook 是 non-singleton
跨 components/hooks 使用都會 new 一個新的 instance

2022-03-04 02:47 UTC, ashramwen commented on src/routes/MainRoutes.jsx
> +        <Route path="Husky/*" element={<Husky />} />
route 建議全小寫，雖然現在的 web server 大多沒問題
但以前有些很擊敗的 server 是 case sensitive 的

2022-03-06 03:59 UTC, HuskyHsu commented on src/pages/Husky/Husky.jsx
> +    </Routes>
```suggestion
    <Routes>
      <Route path="/" element={<AlphaLayout />}>
        <Route index element={<TodoList />} />
        <Route path="todo" element={<TodoList />} />
      </Route>
    </Routes>
```

看了一下這可以算是sub route的做法?
等有多個page再加入XD! 感謝可樂分享

2022-03-06 04:02 UTC, HuskyHsu commented
感謝可樂諸多習慣上的建議
收穫良多~
已更新上去了

2022-03-06 05:42 UTC, ashramwen requested changes

2022-03-06 05:42 UTC, ashramwen commented on src/pages/Husky/TodoList/Add.jsx
> +          onInput={(e) => setNewTalk(e.target.value.trim())}
input 的時候 trim 會變成無法在尾端輸入空白鍵
建議按下 Add 時再 trim

2022-03-06 05:42 UTC, ashramwen commented on src/pages/Husky/TodoList/TodoList.jsx
> +  const methods = new TodoListMethods(todoList, setTodoList);
這邊有點誤會我意思了
我寫一段給你

2022-03-06 05:42 UTC, ashramwen commented on src/pages/Husky/TodoList/TodoList.jsx
> +    this.setData([...this.todoList, ...[task]]);
```js
this.setData([...this.todoList, task]);
```
task 不需要包成 array 再解構

2022-03-06 08:42 UTC, HuskyHsu commented on src/pages/Husky/TodoList/Add.jsx
> +          onInput={(e) => setNewTalk(e.target.value.trim())}
對耶!會遇到這個問題!感謝

2022-03-06 08:42 UTC, HuskyHsu commented on src/pages/Husky/TodoList/TodoList.jsx
> +    this.setData([...this.todoList, ...[task]]);
喔喔喔喔~原來我一直都誤會用法惹...

2022-03-06 08:44 UTC, HuskyHsu commented on src/pages/Husky/TodoList/TodoList.jsx
> +  const methods = new TodoListMethods(todoList, setTodoList);
喔喔~那就變回我最一開始的版本了，後來覺得落落長才切出去XD
感謝示範!

2022-03-06 08:44 UTC, HuskyHsu commented
謝謝可樂再次的review~~(磕頭

2022-03-07 01:41 UTC, ashramwen commented on src/pages/Husky/TodoList/components/utils/Input.jsx
> +      value={value || ''}
```
function Input({ value = '', placeholder, onInput, icon = false }) {
```

2022-03-07 01:41 UTC, ashramwen approved these changes

2022-03-07 01:42 UTC, merged

2022-03-23 05:06 UTC, HuskyHsu commented on src/pages/Husky/TodoList/components/utils/Input.jsx
> +      value={value || ''}
咦，現在才看到ＸＤＤ～
對耶，default要放在component才對